version: '3.9'

services:
  mongo_db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_USERNAME: order
      MONGO_INITDB_PASSWORD: order
      MONGO_INITDB_DATABASE: my_db
    ports:
      - 2717:27017
    volumes:
      - mongo_db:/data/db

  node_app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/home/app
    environment:
      PORT: 3000
      MONGO_URI: mongodb://mongo_db:27017
      DB_NAME: my_db
      DB_USERNAME: order
      DB_PASSWORD: order
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}


